apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: webhookd-demo
  namespace: wiz-operator
rules:
  - apiGroups: ["wiz.rtkwlf.io"]
    resources: ["samlgroupmappings"]
    verbs: ["get", "list", "watch", "create", "patch", "update"]
  - apiGroups: ["wiz.rtkwlf.io"]
    resources: ["samlgroupmappings/status"]
    verbs: ["get", "patch", "update"]
