{{- if .Values.signing.createSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-signing" (include "webhookd.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhookd.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
data:
  webhookSecret: {{ required "signing.secret is required when signing.createSecret=true" .Values.signing.secret | b64enc | quote }}
{{- end }}
