apiVersion: v1
kind: Service
metadata:
  name: {{ include "webhookd.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "webhookd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "webhookd.selectorLabels" . | nindent 4 }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: webhook
      protocol: TCP
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
